feat(polar): implement basic feature
cmpark0126/billboard.js pull request #12
Opened 2021-11-17 06:17 UTC by sni-J

# Issue
#2 

# Details
## 구현 기능

- 데이터 입력, 차트 출력
    - y축에 해당하는 원형 level
    - 반지름으로 값을 표현하는 arc
- 디자인은 [https://www.chartjs.org/docs/latest/charts/polar.html](https://www.chartjs.org/docs/latest/charts/polar.html) 참조, 축 색 등은 Radar 값 재활용
- 데모에 Polar Chart 추가

## 구현 과정

src/ChartInternal/shape 의 radar.ts와 arc.ts를 동시참조하여 필요한 기능만 가져옴
- arc.ts의 경우
    - Donut, Pie 등 각종 배리언트를 내장, Gauge에 대한 공통 처리를 포함하고 있어 불필요한 코드가 많음
    - Polar를 위 경우와 동일시하기에는 다음과 같은 문제가 있음
        1. arc.ts는 d3의 pie (이하 d3Pie)를 활용하고 있는데, 이는 기본적으로 데이터 내 value를 ratio로 환산하여 arc의 중심각을 지정해버림. 따라서 d3Pie의 .value 설정을 Polar의 경우 별도 처리해주어야 함
        2. 동일하게 outerRadius에 대한 설정도 특수하게 변환해주어야 함
        3. level도 또 따로 그려주어야 함
    - Gauge와 같이 추가적인 설정만 하고 대부분의 코드를 arc.ts에서 참조하는 방식을 택하더라도 위의 1, 2는 해결되지 않음
- radar.ts의 경우
    - 데이터 표현이 기본적으로 points로 되어있기 때문에 이에 관한 코드가 뒤섞여있음
    - 또한 두 파일 모두 클릭 또는 호버 이벤트와 같은 추가적(인 줄 알았으나 기본인데 누락한) 기능들에 대한 코드가 있어 이해하는 데에만 한참 걸릴 것으로 판단

## 구현 상세

### demo/
- Polar 추가
### src/ChartInternal/shape/polar.ts
- initPolar
    - 아래 구조로 g 태그 생성
        > CLASS.chartPolars
        ㄴ CLASS.levels
        ㄴ CLASS.chartPolarArcs
        > 
    - 최대 값 설정
        - 가장 큰 값보다 크거나 같은 depth의 배수 중 가장 작은 값
        - 각 level이 정수가 되도록 하기 위함 (별 이유 없이 그냥 그게 보기 좋아서 그렇게 함)
        - chart.js의 경우 간격이나 level 수를 따로 지정할 수 없게 되어있어 나름의 규칙으로 해결한 것으로 보임
        - 나중에는 최대 값도 옵션으로 받게 할 수도 있을 듯
    - d3Pie 초기화
        - value를 1으로 고정하여 각 arc가 동일한 중심각을 갖도록 설정
- getPolarSize: radar 참조, padding은 원형이므로 10으로 고정
- getPolarArc
    - 최대 값과 value의 비율을 반지름으로 환산하여 d3 arc의 outerRadius로 지정 후 반환
        - value의 계산은 arc.ts의 $$.pie 정의 참조
- updateTargetsForPolarArc
    - 주로 arc.ts 참조
    - $el.polar.arcs 안쪽에만 적용해야 하여 chartArcs의 정의만 변경
        - 클래스명으로도 구분은 되지만 앞서 선언해둔 것과 통일성을 위해 이렇게 불러옴
- redrawPolar
    - src/ChartInternal/internals/transform.ts 에 정의한 getTranslate("polar")에 따라 이동
        - 위 좌표 이동에 대한 내용은 후술
    - arcs 추가
        - 주로 arc.ts 참조, transition 제외, text 제외
        - CLASS.arc를 찾아서 데이터 바인드 후, exit - remove / enter - append로 노드 수 재조정, path의 d 속성 지정을 통해 getPolarArc 결과 전달
- updatePolarLevel
    - radar.ts 참조, transition 제외, 좌표계 관련 수정
        - 각 노드를 다루는 부분은 위와 유사
    - 각 circle을 처음부터 중심에 두지 않고 무조건 0,0을 중심으로 하도록 재조정
        - redrawPolar에서 언급한 좌표 이동과 연관
    - text도 유사하게 transform 변경

### src/ChartInternal/internals/transform.ts
- target === "polar" 인 경우는 target === "arc"인 경우와 동일하게 처리
    - 각 arc들을 level circle의 중심 위치로 이동시킨 후 radar와 같은 방식으로 전체 이동을 시키는 것보다 처음부터 level circle을 0,0에 그리고 arc와 동일하게 한 번만 전체 이동을 하는 것이 더 낫다고 판단하였음

### src/config/Options/shape/polar.ts
- level.depth만 넣어둠
- radar와 pie 참고하면서 필요한 옵션을 포함하는 입력 형식을 정하는 것이 최우선으로 진행되어야 할 것 같음

### src/scss/billboard.scss
- radar 스타일에서 axis 삭제, shapes를 polygon에서 path로 변경

### 그 외
- 최소한으로 넣으려고 했으나 한 번 정도 확인 필요

## 알아두면 좋은 내용
- 생각보다 많은 $$의 메소드들이 전역으로 선언되어 있는건지 아니면 전부 import 하면서 그런건지 모르겠으나 이름이 겹치면 꼬이는 경우가 적지 않다

## 확인 필요
- src/ChartInternal/shape/polar.ts
    - `initPolar` -> radar.ts > initRadar에서는 hasType("radar") 여부를 확인하는데 이유를 모르겠음. polar에서는 따로 hasType("polar")를 확인하지 않고 있으나 아직은 큰 문제 없는데 확인 필요
    - 중구난방한 object property 호출 개선
        - `const {polar} = $$.$el;` / `const {$el: {polar}} = $$;` / `const {$el} = $$; $el.polar` 등등...
- src/Chart/api/focus.ts -> focus, defocus, revert에 대해서 별도 구현 필요
    - 현재는 arc.ts의 expand/unexpand를 따르게 되어있어서 이상하게 작동할 것
- src/ChartInternal/ChartInternal.ts: 615~622 -> 일단 써놨으나 개선 필요
- src/config/classes.ts -> 클래스 이름 임시로 설정했으므로 개선 여부 확인 필요
- src/config/const.ts > TYPE_METHOD_NEEDED -> 의미를 이해하지 못해서 Polar는 일단 스킵. 굳이 따지자면 initArc인 듯 하나 의미를 이해한 후 추가해도 될 것 같음
- 커밋이 coverage 테스트를 통과하지 못 했기 때문에 확인 및 개선 필요

2021-11-17 16:31 UTC, cmpark0126 reviewed
* 제가 아직 코드를 정확히 다 본건 아니고 사소한 코멘트만 남겼습니다.
* 내일 다시 보겠습니다.

2021-11-17 16:31 UTC, cmpark0126 commented on demo/demo.js
> +		PolarChart: {
* 사소한 건데 `PolarAreaChart`는 어떨까요? 
* https://www.chartjs.org/docs/latest/charts/polar.html 에서도 `polarArea` type을 사용하는 것 같길래 제안드립니다.

2021-11-17 16:31 UTC, cmpark0126 commented on src/core.ts
> +	 * 	 polar,
* 사소한건데 다른 것들에 비해서 띄어쓰기가 더 들어간 이유가 있나요?

2021-11-18 07:14 UTC, sni-J commented on src/core.ts
> +	 * 	 polar,
없습니다 IDE에서 스페이스/탭 변환하다가 발생한 문제 같네요

2021-11-18 07:20 UTC, sni-J commented on demo/demo.js
> +		PolarChart: {
Polar chart 중에 방향이나 각도로 추가적인 데이터를 표현하는 경우도 있는 것 같으니 현재 구현은 Polar Area Chart가 더 맞는 것 같긴 하네요. 

구현 수준 결정 후
1. Polar 유지 후 현재 구현을 PolarArea의 형태로 하위옵션화
2. PolarArea 단독 구현으로 고정, PolarArea로 이름 변경
중 선택하면 될 것 같습니다.

2021-11-18 13:14 UTC, cmpark0126 commented on demo/demo.js
> +		PolarChart: {
* 저는 PolarArea 단독 구현으로 고정하는게 좋을 것 같습니다.
* Polar를 더 복잡하게 쪼개고 싶다면 나중에 수정해도 될 것 같아서요.
* @HanungLee @grape-tasting-acid @Justin-Moon  의견 부탁드릴게요

2021-11-18 13:18 UTC, cmpark0126 commented on src/core.ts
> +	 * 	 polar,
네 간단한거라 제가 수정했습니다 :)

2021-11-18 13:27 UTC, cmpark0126 commented
@sni-J https://github.com/cmpark0126/billboard.js/pull/12#issue-1055748718
> * 또한 두 파일 모두 클릭 또는 호버 이벤트와 같은 추가적(인 줄 알았으나 기본인데 누락한) 기능들에 대한 코드가 있어 이해하는 데에만 한참 걸릴 것으로 판단
    
여기서 두 파일은, `arc.ts`랑 `radar.ts` 두 개 모두를 의미하는 건가요?

2021-11-18 13:36 UTC, sni-J commented
@cmpark0126 맞습니다. 따로 적은 걸 복붙하면서 뎁스가 바뀌었네요 수정했습니다.

2021-11-18 14:36 UTC, cmpark0126 requested changes
@sni-J  잘 작업해주셔서 감사합니다. 저는 코드 자체에 대한 코멘트는 이 정도로 하겠습니다.
* 제가 사소한 commit을 추가해서 수정을 하시려면 pull을 한번 하시고 작업해주시면 감사하겠습니다.
* 위에 `PolarAreaChart` 관련 코멘트도 한번에 반영되면 좋겠는데 제가 슬랙으로 운을 띄어서 물어보겠습니다. 모두 동의하면 바로 반영하죠.
* 작업을 끝내시고 다시 리뷰 요청하실때는 commit들을 squasy해서 하나로 합쳐주시면 감사하겠습니다.

@HanungLee @grape-tasting-acid  `확인 필요`에 이것저것 이슈를 적어두신 것 같은데 두 분 중 한 분이 작은단위로 쪼개서 Issue를 생성해주실 수 있을까요? 기존 Issue와 관련이 있다면 거기에 코멘트 달아주셔도 좋습니다.

2021-11-18 14:36 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +		$$.polarPie = d3Pie().value(1);
* `1`로 초기화 하는 이유가 주석으로 달려있는 것이 좋을 것 같습니다.
* 혹시 magic number를 피하는 코딩 스타일이 JS 계열에 따로 있을까요? constant variable을 코드 상단에서 정의한다던지... 아니면 method scope 맨 위에서 따로 variable을 정의하고 사용한다던지...

2021-11-18 14:36 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +		const radius = Math.min(width, height);
* 혹시 `width`와 `height`의 경우 무조건 같은 크기인 것은 절대 깨지지 않는 가정일까요?
* 만약 그렇다면 `assert(width == height)`을 하고 `const radius = width`를 하는 것이 더 좋아보이는데 어떻게 보시나요?

2021-11-18 14:36 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +			.innerRadius(0)
* `0`을 사용하는 이유가 주석으로 달려있으면 좋겠습니다.
* 혹시 이런 종류의 magic number를 없앨 수 있는 방안이 있을까요? 제가 JS 계열의 코딩에는 익숙하지 않아서...

2021-11-18 14:36 UTC, cmpark0126 commented on src/ChartInternal/internals/transform.ts
> +			y = state.arcHeight / 2;
* 만약 arc, polar 가 같을 거라면 다음과 같은 형태가 낫지 않나요?: `else if (target === "arc" || target === "polar")`

2021-11-18 14:36 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +			.attr("r", d => levelRatio[d]);
> 각 arc들을 level circle의 중심 위치로 이동시킨 후 radar와 같은 방식으로 전체 이동을 시키는 것보다 처음부터 level circle을 0,0에 그리고 arc와 동일하게 한 번만 전체 이동을 하는 것이 더 낫다고 판단하였음
* 위 코멘트와 관련된 내용인 것 같은데 혹시 위 주석 정도면 충분히 이해가 되겠지요? 보시고 설명이 좀 더 적히면 좋겠다 싶으면 보강해주시고 충분하다고 보시면 이 코멘트는 스킵하셔도 좋습니다.

2021-11-18 14:43 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +		const radius = Math.min(width, height);
`$$.getPolarSize()`를 사용하는 다른 부분에 대해서도 동일한 코멘트 드립니다.

2021-11-18 14:59 UTC, sni-J commented on src/ChartInternal/shape/polar.ts
> +		$$.polarPie = d3Pie().value(1);
- 주석 필요합니다.
- Magic number의 상수화는 권장하고 있습니다.
- d3.pie가 의도한 패턴의 지정이 아니다보니 둘 다 필요할 것 같네요. Method scope에서 하면 될 것 같습니다. 다만 대놓고 안티패턴이다보니 다른 방식의 개선이 있다면 더 좋을 것 같네요

2021-11-18 15:01 UTC, sni-J commented on src/ChartInternal/shape/polar.ts
> +		const radius = Math.min(width, height);
해당 코드는 `radar.ts`를 따른 것으로
- 두 값이 달라질 가능성
- 달라지게 되더라도 둘 중에 작은 값을 사용한다는 semantic
을 기준으로 볼 때 현행 유지가 맞을 것 같습니다.

2021-11-18 15:04 UTC, sni-J commented on src/ChartInternal/shape/polar.ts
> +			.innerRadius(0)
특정한 의미를 갖고 여러 곳에서 사용되는 매직넘버의 경우 클린코드 관점에서 상수화 하여 소거하는 것이 맞겠으나, 해당 0은 단순히 arc의 내부 반지름을 0으로 지정하는 것으로 별도의 수정이 필요할 것 같지 않습니다. 0이라는 값으로 왜 지정했는지 그 의미가 불분명한 사례도 아니므로 넘어가도 될 듯 합니다.

2021-11-18 15:11 UTC, sni-J commented on src/ChartInternal/internals/transform.ts
> +			y = state.arcHeight / 2;
향후 arc가 업데이트되어도 polar는 독립적으로 현재 형태를 유지해야하기 때문이라고 생각하여 분리하였습니다. 항상 완전히 동일하다면 polar 내에서도 "arc"로 타겟을 지정하면 되겠지만 구현체 자체가 분리되어있고 그러한 이유로 타겟도 분리하였기에 조건문 역시 분리하는 것이 좋아보입니다.

2021-11-18 17:21 UTC, Justin-Moon commented on demo/demo.js
> +		PolarChart: {
넵 polar area로 가시죠!

2021-11-19 01:15 UTC, HanungLee commented on demo/demo.js
> +		PolarChart: {
저도 PolarArea로 하고 추후에 수정하는 것이 좋아보입니다~

2021-11-19 01:47 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +		$$.polarPie = d3Pie().value(1);
@sni-J 네 작업 부탁드립니다 :)

2021-11-19 01:48 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +		const radius = Math.min(width, height);
@sni-J 동의합니다 :)

2021-11-19 01:48 UTC, cmpark0126 commented on src/ChartInternal/internals/transform.ts
> +			y = state.arcHeight / 2;
@sni-J 동의합니다 :)

2021-11-19 01:48 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +			.innerRadius(0)
@sni-J 알겠습니다 :)

2021-11-19 05:43 UTC, cmpark0126 commented on demo/demo.js
> +		PolarChart: {
@sni-J 과반수가 동의한 것 같습니다. 수정 부탁드려요 :)

2021-11-19 05:51 UTC, sni-J commented on demo/demo.js
> +		PolarChart: {
@cmpark0126 @HanungLee @Justin-Moon Polar를 PolarArea로 변경하게 되면 이 부분 뿐만 아니라 많은 부분의 polar를 전부 리네이밍해야하는데 굳이 그럴 필요가 있을까요?

2021-11-19 05:53 UTC, cmpark0126 commented on demo/demo.js
> +		PolarChart: {
저는 큰 공수가 들지 않는다면 바꾸는 것이 맞다고 생각하는데요. 이건 뭔가 scientific한 이유가 있는 의견이 아니라 저는 다수의 의견에 따로도록 하겠습니다.

2021-11-19 07:29 UTC, cmpark0126 commented on demo/demo.js
> +		PolarChart: {
@sni-J 당연히 오픈소스로서 많은 기능을 제공하겠다는 포부를 가지는 것은 좋다고 생각합니다. 하지만 처음부터 기능을 모두 뚫을 것이 아니라면 area chart로 이름을 한정하고 개발을 시작하는 것이 맞다고 생각합니다. 언제 새로운 기능을 추가할지도 모르는 상황이구요. 그렇다면 괜히 다른 옵션이 있다는 기대를 심어주지 않는 것이 맞다고 생각합니다. 어차피 나중에 새로운 기능을 추가하면서 이름을 바꾸는게 그렇게 어려워보이지도 않구요.

2021-11-19 07:30 UTC, cmpark0126 commented on demo/demo.js
> +		PolarChart: {
아니면 추후에 어떤 종류의 polar 기능을 추가할 것인지 TODO로 제대로 남겨둔다면 Polar를 유지하는 것에도 동의합니다.

2021-11-20 09:58 UTC, HanungLee commented on demo/demo.js
> +		PolarChart: {
저도 명칭을 바꾸자고 제안하긴 했지만, 고치는 양이 많다면 굳이 안 해도 될 것 같습니다. 빌보드에서 다른 PolarChart가 현재 존재하는 것이 아니기 때문에, 기본 구현된 PolarAreaChart를 PolarChart로 부른다고 해서 오해가 생길 일은 딱히 없을 것 같아서요. 나중에 PolarChart의 기능을 추가하는 시점에서 결정해도 될 문제인 것 같습니다.

2021-11-20 10:01 UTC, HanungLee commented
이슈는 #14 만 추가해두었습니다. 다른 내용들 중에서 마우스 hover에 대한 행동이나 테스트 커버 등은 이미 존재하는 이슈인 것 같고, 다른 내용들은 작업 중에 참고하거나, 다른 작업에서 의미를 파악해야 하는 경우들인 것 같아서 이슈화하기는 어려운 것 같습니다. 

그런데 이 PR에서 작업 완료되었으면 바로 스쿼시 머지 해도 괜찮지 않나요? 다시 리뷰요청을 해야하는 이유가 있을까요? 다시 리뷰요청하는 의미를 제가 잘 몰라서요, 설명해주시면 감사하겠습니다!

2021-11-20 10:02 UTC, HanungLee approved these changes

2021-11-21 06:03 UTC, cmpark0126 commented
> 이슈는 #14 만 추가해두었습니다. 다른 내용들 중에서 마우스 hover에 대한 행동이나 테스트 커버 등은 이미 존재하는 이슈인 것 같고, 다른 내용들은 작업 중에 참고하거나, 다른 작업에서 의미를 파악해야 하는 경우들인 것 같아서 이슈화하기는 어려운 것 같습니다.
> 
> 그런데 이 PR에서 작업 완료되었으면 바로 스쿼시 머지 해도 괜찮지 않나요? 다시 리뷰요청을 해야하는 이유가 있을까요? 다시 리뷰요청하는 의미를 제가 잘 몰라서요, 설명해주시면 감사하겠습니다!

* 다른 작업에서 의미를 파악해야 하는 경우들이라도 어떻게든 이슈화를 해야 나중에 기억을 할 수 있을 것 같습니다. 대충이라도 이슈화 해주시면 감사하겠습니다.
* 작업 완료했으면 당연히 바로 스쿼시 머지해도 되구요. 다시 리뷰 요청하실 필요 없습니다.

2021-11-21 07:36 UTC, merged

2021-11-24 06:58 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +			.merge(mainArc)
* 혹시 이 두 라인이 어떤 동작을 보이는 코드인지 알 수 있을까요?

2021-11-24 07:00 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +		if (translate) {
polar 면 무조건 if (translate) 는 통과하는 것 같은데 맞나요? 만약 그렇다면 if condition을 빼도 될까요?

2021-11-24 07:30 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +			.attr("class", (d, i) => `${CLASS.level} ${CLASS.level}-${i}`);
여기서 d는 안 쓰이는 것 같네요. 삭제해도 괜찮을까요?

2021-11-24 07:37 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +		levelEnter.merge(level);
이 코드도 꼭 필요한가요? 삭제해도 정상적으로 동작하는 것 같길래 왜 필요한지 여쭤보고 싶습니다.

2021-11-24 08:06 UTC, sni-J commented on src/ChartInternal/shape/polar.ts
> +			.merge(mainArc)
redrawPolar 함수 자체는 arc.ts의 redrawArc 함수에서 변형한 구조인데요,
- `.each(~~` 에서 정의하는 `this._current`의 경우 기존 코드에서는 opacity를 조절하기 위해 참조하거나 각도를 interpolate하는 과정에서 필요한 변수로 할당되어 있습니다. 주로 legend에서의 클릭 후 transition을 처리하는 쪽에 관련되어 있는데 이 관련 코드를 제거하다가 남은 것으로 보입니다. 
- `.merge(mainArc)` 역시 위와 유사하게 transition을 적용할 때, 해당 path 뿐만 아니라 그 상위에 해당하는 g 태그 (CLASS.arc; `bb-chart-arc`)도 opacity 변환에 포함되어야 하기 때문에 mainArc 변수에 이를 포함시키기 위해 작성된 것으로 이해하고 있습니다.

2021-11-24 14:10 UTC, sni-J commented on src/ChartInternal/shape/polar.ts
> +		if (translate) {
redrawRadar를 참조하였습니다. 
이외의 $$.getTranslate 활용 케이스들을 살펴보면 별도 변수로도 빼지 않고 바로 attr에 전달한 것으로 보아 77번째 줄을 `polar.attr("transform", $$.getTranslate("polar"));` 로 변경해도 큰 문제 없을 것 같긴 하네요

2021-11-24 14:15 UTC, sni-J commented on src/ChartInternal/shape/polar.ts
> +			.attr("class", (d, i) => `${CLASS.level} ${CLASS.level}-${i}`);
d를 삭제한다는 의미가 무슨 의미인지 모르겠네요... 설마 두 번째 파라미터를 
```
(i) => `${CLASS.level} ${CLASS.level}-${i}`
``` 
로 변경하자는 말씀이신가요?

2021-11-24 14:17 UTC, sni-J commented on src/ChartInternal/shape/polar.ts
> +		levelEnter.merge(level);
levelEnter 하위 노드들을 전부 merge 후 한 번에 translate 하던 코드의 일부였던 것으로 보입니다.
level과 data를 한 번에 translate 하기로 하면서 같이 제거되었어야 하는데 남아있게 된 것 같네요. 지금 구현 상으로는 제거해도 문제 없습니다.

2021-12-06 17:03 UTC, cmpark0126 commented on src/ChartInternal/shape/polar.ts
> +			.attr("class", (d, i) => `${CLASS.level} ${CLASS.level}-${i}`);
아뇨 _를 붙이는 것을 제안했습니다.